pomogi1/config/routes.rb
Rails.application.routes.draw do

root 'index#index'
resources :todos
end

pomogi1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pomogi1/app/models/project.rb
class Project < ApplicationRecord
	has_many :todos
end

pomogi1/app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :project
end

pomogi1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

pomogi1/app/controllers/create_controller.rb
class CreateController < ApplicationController
end

pomogi1/app/controllers/index_controller.rb
class IndexController < ApplicationController
	def index
		@f = 0
		@Todo1 = Todo.where(project_id:1)
		@Todo2 = Todo.where(project_id:2)
		@Todo3 = Todo.where(project_id:3)
	end

def show

end

end

pomogi1/app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def create
		@h = Todo.all
		@d = Todo.create(brand_params)
		@r = Todo.all
		@r.each do |g|
		@ids = g.id
		end
		@i = Todo.find(@ids)
			@h.each do |t|
				if (t.text == @i.text) && !(t.id == @i.id) && (t.project_id == @i.project_id)
					t.destroy
					break
				end
			end
			
	end
    def brand_params
     @brand_params = params.require(:todos).permit(:text, :project_id, :isCompleted)
    end
end

pomogi1/app/helpers/application_helper.rb
module ApplicationHelper
end

pomogi1/app/helpers/create_helper.rb
module CreateHelper
end

pomogi1/app/helpers/index_helper.rb
module IndexHelper
end

pomogi1/app/helpers/todos_helper.rb
module TodosHelper
end

pomogi1/app/views/index/index.html.erb
<div class="divm"><div class="divtitle">Задачи</div><b><div class="atitle"><a class="afix" href="#" onclick="openform()">+</a></div></b></div>
	<script type="text/javascript">
		function update(x) {
			var h = 0;
		text = document.getElementById(x+'text').innerHTML;
		com = document.getElementById(x+'com').innerHTML;
		id = document.getElementById(x+'id').innerHTML;
		document.getElementById('todos_text').value = text;
		document.getElementById('todos_project_id').value = id;
			if (com == "false") {
				document.getElementById('todos_isCompleted').value = true;
			} else{
				document.getElementById('todos_isCompleted').value = false;
			}
		document.forms["formform"].submit();
		setTimeout(function() {location.reload();}, 1000);
		}
	</script>
<table>
	<tr>
<td class="uld">
<div class="nameul"><b>СЕМЬЯ</b></div>

	<ul>
		<%= @Todo1.find_each do |t| %>
		<%= 
			if (t.isCompleted==false)
				puts @g = 'noneline', @c=' ', @r = "false"
			else
				puts @g = 'line', @c="checked='true'", @r = "true"	 
			end
		%>
		<li>
			<input type="checkbox" class="fixbox" disabled <%= @c %>>
			<div id="<%= @f=@f+1 %>" class="<%= @g %>">
				<a href="#" onclick="update(<%= @f %>)">
					<div id="<%= @f %>text" class="colorfix"><%=  t.text  %></div>
				<div class="nonevision">
					<div id="<%= @f %>com"><%= @r %></div>
					<div id="<%= @f %>id"><%= t.project_id %></div>
				</div>
				</a>
			</div>
		</li>
		<% end %>
	</ul>
</td>
<td class="uld">
<div class="nameul"><b>РАБОТА</b></div>
	<ul>
		<%= @Todo2.find_each do |t| %>
		<%= 
			if (t.isCompleted==false)
				puts @g = 'noneline', @c=' ', @r = "false"
			else
				puts @g = 'line', @c="checked='true'", @r = "true"	 
			end
		%>
		<li>
			<input type="checkbox" name="<%= @f = @f+1 %>"  class="fixbox" disabled <%= @c %>>
			<div id="<%= @f %>" class="<%= @g %>">
				<a href="#" onclick="update(<%= @f %>)">
					<div id="<%= @f %>text" class="colorfix"><%=  t.text  %></div>
				<div class="nonevision">
					<div id="<%= @f %>com"><%= @r %></div>
					<div id="<%= @f %>id"><%= t.project_id %></div>
				</div>
				</a>
			</div>
		</li>
		<% end %>
	</ul>
</td>
<td class="uld">
<div class="nameul"><b>ПРОЧЕЕ</b></div>
	<ul>
		<%= @Todo3.find_each do |t| %>
		<%= 
			if (t.isCompleted==false)
				puts @g = 'noneline', @c=' ', @r = "false"
			else
				puts @g = 'line', @c="checked='true'", @r = "true"	 
			end
		%>
		<li>
			<input type="checkbox" name="<%= @f = @f+1 %>"  class="fixbox" disabled <%= @c %>>
			<div id="<%= @f %>" class="<%= @g %>">
				<a href="#" onclick="update(<%= @f %>)">
					<div id="<%= @f %>text" class="colorfix"><%=  t.text  %></div>
				<div class="nonevision">
					<div id="<%= @f %>com"><%= @r %></div>
					<div id="<%= @f %>id"><%= t.project_id %></div>
				</div>		
				</a>
			</div>
		</li>
		<% end %>
	</ul>
</td>
</tr>
</table> 
<div id="myform"> 
<div class="fade"></div>
<div class="formcreate">
	<div class="nameul"><b class="fixb" >НОВАЯ ЗАДАЧА</b></div>
	<%= form_for :todos, url: todos_path, :html =>{:id => "formform"} do |f| %>
		<br>
		<div class="buttons">
    		<%= f.text_field  :text %>
    		
    		<%= f.text_field  :isCompleted, :value => false  %>
  		</div>	
		<br>
		<div class="buttons">
			<%= f.select :project_id, options_for_select([['Семья', 1], ['Работа', 2], ['Прочее', 3]]) %>
		</div>
		<br>
			<div class="buttons">
				<a href="#" onclick="closeform()">
					<div id="fixbutton" class="abutton">
						<div class="texta">ОТМЕНА</div>
					</div>
				</a>
				<a href="#" onclick="save()">
					<div class="abutton">
						<div class="texta">ОК</div>
					</div>
				</a>
			</div>
	<% end %>
</div>

pomogi1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<style type="text/css">
      .colorfix{
        color:black;
      }
      .nonevision{
        display:none;
      }
      #todos_isCompleted{
        display: none;
      }
      .fixb{
        text-align:center;
      }
      .fixbox{
        margin-left: -20px;
      }
      .noneline{
        margin-top:-19px;
      }
      .line{
        margin-top:-19px;
        text-decoration:line-through;
      }
      li{
        list-style-type: none;
        padding-bottom:20px;
        margin-left:auto;
        margin-right:auto;
      }
      #todos_project_id{
        width:355px;
        height:50px;
      }
      #todos_text{
        width:350px;
        height:50px;
      }
      .buttons{
        width:360px;
        margin-right:auto;
        margin-left:auto;
              }
      .abutton{
        text-align:center;
        width:170px;
        height:50px;
        background-color:rgb(58 175 218);
        color:white;
        display:inline-block;
       
        
      }
      #fixbutton{
        background-color: rgb(159 159 159);
        margin-right:10px;
      }
      .nameul{
        border-bottom:1px solid lightgray;
        width:100%-10px;
        padding:10px;
      }
      body{
        font-family: sans-serif;
        width:100%;
        height:800px;
      }
      .formcreate{
        width:30%;
        min-width:400px;
        height:280px;
        background-color:white;
        position:absolute;
        top:200px;
        margin-left: 35%;
        
      }
      .fade{
        position:absolute;
        top:0px;
        width:100%;
        height:800px;
        opacity:0.8;
        background-color:black;
      }
      a{
        text-decoration:none;
      }
      .afix{
        color: white;
        font-size:40px;
      }
      .atitle{
        width:100px;
        height:70px;
        margin-top:-67px;
        margin-left:95%;
        color: white;
      }
      .divtitle{
        padding-top:7px;
        font-size:40px;
        margin: auto;
        text-align:center;
        width:100px;
        height:70px;
        color: white;
       
      }
      .divm{
        position:relative;

        width:100%;
        height:70px;
        background-color:rgb(58 175 218);
      }
      table{
        margin-top:30px;
        width:95%;
        margin-right: auto;
        margin-left: auto;   
      }
  		.uld{
        font-size:14px;
        background-color:white;
  			float: left; 
        margin-left:2.5%; 
  			width:30%;
  			min-height:220px;
        -webkit-box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.75);
        -moz-box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.75);
        box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.75);
  		}
  	  body{
        background-color:rgb(248 248 248);
      }
  	  .texta{
        margin-top:15px;
      }
  	</style>
    <title>Приложение</title>
	  <%= csrf_meta_tags %>
<script type="text/javascript">
    function save() { 
    document.forms["formform"].submit();
     setTimeout(function() {location.reload();}, 1000);
    }
    function  closeform() {
    document.getElementById('myform').style.display='none';
    }
    function openform() {
    document.getElementById('myform').style.display='block';
    }
</script>
</head>

  <body  onload="closeform()">
    <%= yield %>
  </body>
</html>